platform: linux

image_resource:
  type: docker-image
  source:
    repository: microsoft/dotnet
    tag: 2.1-sdk

inputs:
  - name: repo

outputs:
  - name: published

run:
  path: ./repo/ci/tasks/build.sh